### ISSUE TITLE
confidence is always returned as 0.0

### ISSUE THREAD

**Issue by oziee** [golastmile/rasa_nlu#102]
hi.. you are doing some great stuff here with rasa:)

I have followed all the sets and trained etc and when I run this command "python -m rasa_nlu.server -c config.json" the confidence is 0.0

> {
    "entities": [
      {
        "start": 4, 
        "end": 9, 
        "value": "bread", 
        "entity": "shoppingItem"
      }
    ], 
    "confidence": 0.0, 
    "intent": "\"shoppingList\"", 
    "text": "add bread to the shopping list"
  }

this text example is an exact match to one of the items in the training data

testing a sentence which is definitely not anything like in the training data still links to the intent with a 0 confidence.. simply sending "hello" as the string

> {
    "entities": [
      {
        "start": 0, 
        "end": 5, 
        "value": "hello", 
        "entity": "shoppingItem"
      }
    ], 
    "confidence": 0.0, 
    "intent": "\"shoppingList\"", 
    "text": "hello"
  }

all the training data are sentences including wording 'shopping list'.. a one word query of "hello" I would have expected it not to match it to anything at all.. I am guessing that I might have to include a new entity for testing that "shopping list" is in the sentence..

but why is the confidence always 0.0

If I run the server as just the demo and say hello.. "confidence": 1.0, "intent": "greet" so this does calc confidence.. so is it just custom training data this is failing on?

also as a side note.. which does rasa prefer? Mitie or spaCy + scikit-learn ?

**Comment by tmbo** [comment]
which backend are you using?

**Comment by oziee** [comment]
mitie

**Comment by tmbo** [comment]
@oziee I could not reproduce the issue yet. I'd need some more information to do so.

The default of `confidence: 1.0` is due to the default `Hello-Goodby` backend, which always returns a confidence of 1.0. this default backend is used if the server is started and no model directory is specified (I added a warning in this case, so it is clear for the user that not the specified model, e.g. mitie, is used).

For a trained model using the default data it works just fine and I get confidence values that are neither 0.0 nor 1.0.

Can you please send me the configuration you used for train / start?

**Comment by oziee** [comment]
here is a zip of my whole directory without the total_word_feature_extractor.dat file in the data directory (way to big :) all the training and other files etc

the original Wit file for training is in the data/expressions.json

config files etc are all there too

Oz

**Comment by tmbo** [comment]
Alright I ran your model and now I can reproduce the 0.0 confidence score.

Solution: add more intents. There is only a single intent, hence every message gets classified with this intent and mitie assigns this classification a confidence of 0.0.

Hence, this is a mitie bug which you can circumvent by using more than one intent.
