### ISSUE TITLE
Add Intents Priority for API.AI

### ISSUE THREAD

**Issue by vaggosifa** [golastmile/rasa_nlu#118]
Intent priority allows to assign more weight to one of the intent in case an input phrase matches multiple intents.
from [API.AI Docs](https://docs.api.ai/docs/concept-intents#intents-priority)

**Comment by amitbend** [comment]
I think you should handle it on your end, you will get a score for the intent - so you give more weight once you get the response from Rasa

**Comment by amn41** [comment]
thanks for creating this issue. Because rasa uses a probabilistic model, there is no concept of "matching" or "not matching". We could return multiple intents if the confidence is low - 
do you have a specific example where you would have a sensible fallback?

Agree with @amitbend 's comment. It is usually easier to have really clearly defined intents, and if you get a low confidence just ask the user to rephrase or some other fallback.

**Comment by vaggosifa** [comment]
OK Thank's
