### ISSUE TITLE
Use Duckling for date/distance/... parsing

### ISSUE THREAD

**Issue by rafael-aero** [golastmile/rasa_nlu#125]
If anyone feels like integrating duckling to rasa-nlu, I've made a simple rest-server for interacting with it:
https://github.com/rafael-aero/resting_duckling/

**Comment by amn41** [comment]
Looks cool! As I understand it duckling on it's own doesn't handle entity extraction right? So it can turn a phrase like "next wednesday" into a `DateTime`, but it wouldn't necessarily behave well if you sent it "place an order for next wednesday", so you would have to use rasa to extract the phrase first. Is that right? 
I can definitely see the use in this, if you get something working we can write up some documentation.

**Comment by tmbo** [comment]
There is also a python wrapper around duckling https://github.com/FraBle/python-duckling. Not sure which one is easier to use. But anyway this should be rather easy to do

**Comment by rafael-aero** [comment]
@tmbo: the python wrapper seems like the most natural approach - of course with the same caveats of depending on the JVM, and the quite long loading times for clojure.

**Comment by tmbo** [comment]
I'd say that is not to big of an issue. First, because we'd only use it if the user decides to do so (so he would be aware of the loading time) and second, we try to move rasa nlu to be a server application hence, we want to avoid the need for restarts (because of the model & backend loading times). Nevertheless, the loading time is something to be aware of.

**Comment by twerkmeister** [comment]
Solved by PR #258 - closing
