### ISSUE TITLE
Training rasa NLU from python 

### ISSUE THREAD

**Issue by AndriiKr** [golastmile/rasa_nlu#167]
Hi,
I just tried parse data in python like in example http://rasa-nlu.readthedocs.io/en/latest/python.html and it's works great. I tried to train using classes but failed with 

> TypeError: train() got an unexpected keyword argument 'entity_examples'

Code snippet
```
    config = json.loads(open(os.path.abspath('config_spacy.json')).read())
    trainer = SpacySklearnTrainer(config, "en", 1)
    trainingData = json.loads(open(os.path.abspath('traine/demo-rasa.json')).read())
    trn = trainer.train(**trainingData['rasa_nlu_data'])
```
As I understand from doc 

> For creating your models, follow the same instructions as non-python users.

There are no way to train rasa_nlu directly in python?
Thanks

**Comment by amn41** [comment]
You can ! Something like this should work (I'll add this to documentation as well)

```python
from rasa_nlu.training_data import TrainingData
from rasa_nlu.trainers.spacy_sklearn_trainer import SpacySklearnTrainer

training_data = TrainingData('data/dataset.json', 'spacy_sklearn', 'en')
trainer.train(training_data)
trainer.persist('models/')
```

**Comment by AndriiKr** [comment]
Thanks so much!

**Comment by shuvayan** [comment]
Hello ,
While using the command:
from rasa_nlu.trainers.spacy_sklearn_trainer import SpacySklearnTrainer
 I am getting error as ImportError: No module named 'rasa_nlu.trainers'
I have installed rasa_nlu from PyPI using pip.

Please tell me how to resolve this.

**Comment by tmbo** [comment]
@shuvayan This example is for an older version of rasa NLU. You can find the latest documentation on how to use rasa NLU from python here: https://rasa-nlu.readthedocs.io/en/stable/python.html

Let me know if something is missing there or if something is unclear / not working.

**Comment by shuvayan** [comment]
Hello @tmbo ,
Thanks for the prompt reply. That issue got resolved but now there is another issue with pycrfsuite as shown below:

`from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer
#import en_core_web_sm as en

training_data = load_data('./data/demo-rasa.json')
trainer = Trainer(RasaNLUConfig("config.json"))
trainer.train(training_data)
model_directory = trainer.persist('./models/')  

Traceback (most recent call last):

  File "<ipython-input-1-4bb33aa876fc>", line 12, in <module>
    trainer.train(training_data)

  File "C:\Users\shuvayan.das\AppData\Local\Continuum\Anaconda3.3\lib\site-packages\rasa_nlu\model.py", line 157, in train
    updates = component.train(*args)

  File "C:\Users\shuvayan.das\AppData\Local\Continuum\Anaconda3.3\lib\site-packages\rasa_nlu\extractors\crf_entity_extractor.py", line 80, in train
    self._train_model(dataset)

  File "C:\Users\shuvayan.das\AppData\Local\Continuum\Anaconda3.3\lib\site-packages\rasa_nlu\extractors\crf_entity_extractor.py", line 308, in _train_model
    self.ent_tagger.open(self.crf_file.name)

  File "pycrfsuite/_pycrfsuite.pyx", line 571, in pycrfsuite._pycrfsuite.Tagger.open (pycrfsuite/_pycrfsuite.cpp:7731)

  File "pycrfsuite/_pycrfsuite.pyx", line 717, in pycrfsuite._pycrfsuite.Tagger._check_model (pycrfsuite/_pycrfsuite.cpp:10037)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\shuvayan.das\\AppData\\Local\\Temp\\tmps0o4nwg9'`

Is this due to some issue in rasa_nlu or pycrfsuite? I am guessing I am not being able to access the cpp file. Can you please help on this??

**Comment by ramkumar-mn** [comment]
Could anyone share a example that is using rasa nlu installed using python(pip install rasa_nlu).I am confused with the flow(how to proceed)

**Comment by wrathagom** [comment]
@ramkumar-mn have you seen he docs located [here](http://rasa-nlu.readthedocs.io/en/latest/installation.html#setting-up-rasa-nlu)?

If those don't help you can you join us on [Gitter](https://gitter.im/RasaHQ/rasa_nlu) to discuss more or create a [new issue](https://github.com/RasaHQ/rasa_nlu/issues/new). Looks like this issue pertains to something different.

**Comment by Brijeshlakkad** [comment]
I have upgraded to version 11.5 and problem solved:

pip install rasa-nlu==0.11.5
