### ISSUE TITLE
entities: list or dict?

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#20]
@plauto you mentioned there was some confusion around when entities is a `dict` and when it's a `list`. Let's figure out what exactly is wrong

**Comment by plauto** [comment]
The problem was related to HelloGoodbyeInterpreter. There we send a dummy response where entity is a list.  

Instead, when we start the server by specifying a model we have previously trained everything works fine if we consider entity as dict.

Btw, this raised another issue. If you train the luis model we have in /data there seems to be an issue with the tokenizer.
