### ISSUE TITLE
tests for train.py and server.py

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#22]
these scripts are currently not well covered by unit tests. I think coveralls doesn't report that because they're considered 'outside' the `rasa_nlu` module

**Comment by plauto** [comment]
ok - gonna look into that! Do you want me to find a way of getting them noticed by coveralls as well?

**Comment by amn41** [comment]
yes please!

**Comment by plauto** [comment]
now we have some tests for server.py. (we can write more anyway!)
I was just curious if we actually need tests for train.py since we are stimulating its method do_train with the tests for server.py (do_train gets called directly by the main of train.py as its entry point)...and test_training_data already tests specific trainers somehow. What do you think?
