### ISSUE TITLE
Leveraging Default NER

### ISSUE THREAD

**Issue by SVehrenkamp** [golastmile/rasa_nlu#233]
Is there currently a way to leverage the default NER model that ships with spaCy?

It would be nice to be able to extract default entities defined here:
https://spacy.io/docs/usage/entity-recognition#entity-types
in addition to training a custom model.

Any thoughts on how this could be possible?

**Comment by tmbo** [comment]
You can use the default NER entities from spacy with rasa NLU. 

There is a configuration flag called `fine_tune_spacy_ner` which you need to set to true to use the existing spacy entities (see https://rasa-nlu.readthedocs.io/en/stable/config.html, if you are using the current master, make sure to switch the doc to LATEST instead of STABLE). 

Unfortunately, the fine tuning is broken in the current version of spacy (#910), so what we are currently doing if you set that flag to true is the following:
- we'll train a new ner model using your entities
- during evaluation we will do entity extraction using your model and the spacy model and merge the results.

Our goal is though to fix the fine tuning to use one model again.
