### ISSUE TITLE
Intent Recognized InCorrect

### ISSUE THREAD

**Issue by liuhebian** [golastmile/rasa_nlu#277]
**rasa NLU version** `0.7.2`

**Used backend / pipeline** spacy_sklearn

**Operating system**:windows,

**Issue**:

I try to build a FAQ NLP engine, I loaded 500 questions into RASA NLU, in my data file, I use question as "intent" and "text". So I have 500 intent and 500 training text. After deploy, I found even I use exact question to test RASA NLU, I often get a wrong intent with low confidence (0.0xx).

**Comment by tmbo** [comment]
Unfortunately, these are too many intents with too few training examples. For the machine learning model to properly distinguish between the different questions, you would need way more training examples for each question. 

Since, FAQ is a very specific (but also quite different use case from "normal" chat interactions) we are thinking about different solutions here as well. We don't have a ready to use solution yet but if you feel adventurous there is a lot of research about this topice, e.g. http://ijcai.org/Proceedings/15/Papers/188.pdf
