### ISSUE TITLE
Deploy new models with zero downtime

### ISSUE THREAD

**Issue by srijiths** [golastmile/rasa_nlu#342]
It would be a good feature if we can deploy new models with out shutting down the running rasa http server. Right now , if we bring rasa in production and if we wanted to deploy a new model with rasa , then we have to bring the rasa server down. This will affect the running models.

**Comment by twerkmeister** [comment]
Hey srijiths, totally on our list and I agree it's a much needed feature! The implementation of this feature would mostly concern the data router component. If you can make the time it would a opportunity to make a great contribution to rasa. Could you support us with this one?

**Comment by srijiths** [comment]
@twerkmeister I am just a python beginner. But still , if you can point me where to look at , i would be glad to contribute. :)

**Comment by twerkmeister** [comment]
@srijiths @sergmetelin sorry for the confusion I caused. Turns out the functionality has been implemented already. In the lines following https://github.com/golastmile/rasa_nlu/blob/master/rasa_nlu/data_router.py#L151 the data router checks if the alias is found in the model store and otherwise loads it from disk! Closing this.
