### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by amn41** [golastmile/rasa_nlu#68]
Currently code doesn't work with python 3.

**Comment by devenbhooshan** [comment]
Hello guys. Kudos for the launch.

How much effort is needed to resolve this issue ?
What do you guys think?

**Comment by HintikkaKimmo** [comment]
Just find the project and first great job. I've been looking for something like this. On the issue, I might be able to help. Progressbar surely does not work in python3 but there is Python3 fork besides that lets see what happens when I run 2to3 on the project.

**Comment by HintikkaKimmo** [comment]
Ok it's now running on Python 3.5.2 but bit of a hack

**Comment by HintikkaKimmo** [comment]
Could someone give a little direction here, Admittedly I only spend about an hour to migrate a rather sizable project and got it running (2 tests are still failing due to type issues). However, my quick fork wouldn't work with Python 2.7, because I did not write backward compatible way and one of the dependencies progressbar was changed to progressbar2. Is there a plan to make the whole project run on both python versions? 

If that is the case I can start to contribute small commits file by file, but I have no idea what to do with progressbar and how to make it handle byte data allowing Python2 to still understood what is happening.

**Comment by amn41** [comment]
Hi Kimmo, thanks very much for looking into this. We can replace progressbar with [tqdm](https://pypi.python.org/pypi/tqdm) . I will try to find someone who can help make the code cross-compatible as well.

**Comment by razeone** [comment]
Is there any branch, issues, or something to help with?

**Comment by amn41** [comment]
@twerkmeister FYI please branch from `pipeline` not master
